### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by XVincentX** [XVincentX/pollsApiClient#39]
- [x] Pagination is not working (not implemented server side, could be implemented client side with infinite scrolling)

- [ ] Add a bit more serious testing. Furthermore, the good of protractor is that can get elements on directives. Take more advantage of that

- [ ] Execute unit tests on Saucelabs as well

- [ ] Tests are playing with the production **apiUrl**. It is cool (since the initial state gets restored) but perhaps would be a better idea to play on the Apiary mock server

- [ ] Validation is written on the client. It should be verified if the server is sending data when inputs are not valid, and parse them appropriately

- [ ] If an action fail, would be great to display some error message, somewhere 

- [ ] I feel that I should not rely on `$promise` property of hy-res.

- [x] PollsAPI supports now pagination. Use it. (Quite urgent) #40 

- [ ] `application.css` contains stuff that should not be there

- [ ] Introduce the usage of **ImmutableJS**

- [x] Add a _Refresh_ button

- [ ] Review the animations, they are not every time the appropriate ones

- [x] Vote action is hardcoded

- [x] Angular-mocks is installed as a bower dependency. Use npm

- [ ] Use `ng-describe` to test the angular application

- [x] Lint the code using esLint #45

**Comment by petejohanson** [comment]
So you know, angular-hy-res tries as much as possible for the `$followOne` and `$followAll` calls to work on a resource that isn't yet resolved. So you should be able to do:

    hrRoot(apiLocation).follow().$followOne('questions').$followAll('questions')

And the resulting array will eventually be populated w/ the embedded resources in the final resource. So you could databind to that final result to iterate, or use the `$promise` property on the final result and it should eventually resolve as expected.

That should help you cut down on at least some of your promise logic in the polls service.

**Comment by XVincentX** [comment]
Thanks. I definitely felt that was missing something, and your approach should improve the code.
Please, feel free to add your other thoughts as well here.

**Comment by XVincentX** [comment]
Nothing more is going on here.
